// panel_admin/src/components/Layout.vue
<template>
  <div class="d-flex">
    <!-- Sidebar -->
    <nav class="sidebar col-md-3 col-lg-2 d-md-block">
      <div class="position-sticky pt-3">
        <div class="px-3 mb-4">
          <h5 class="text-white">Static CMS</h5>
          <small class="text-muted">Panel Admin</small>
        </div>
        
        <ul class="nav flex-column">
          <li class="nav-item">
            <router-link to="/dashboard" class="nav-link" active-class="active">
              <i class="bi bi-speedometer2 me-2"></i>
              Dashboard
            </router-link>
          </li>
          <li class="nav-item">
            <router-link to="/pages" class="nav-link" active-class="active">
              <i class="bi bi-file-text me-2"></i>
              Páginas
            </router-link>
          </li>
          <li class="nav-item">
            <router-link to="/content-types" class="nav-link" active-class="active">
              <i class="bi bi-collection me-2"></i>
              Tipos de Contenido
            </router-link>
          </li>
          <li class="nav-item">
            <router-link to="/views" class="nav-link" active-class="active">
              <i class="bi bi-eye me-2"></i>
              Vistas
            </router-link>
          </li>
          <li class="nav-item">
            <router-link to="/media" class="nav-link" active-class="active">
              <i class="bi bi-images me-2"></i>
              Multimedia
            </router-link>
          </li>
          <li class="nav-item">
            <router-link to="/formatters" class="nav-link" active-class="active">
              <i class="bi bi-code-slash me-2"></i>
              Formateadores
            </router-link>
          </li>
          <li class="nav-item">
            <router-link to="/site-builder" class="nav-link" active-class="active">
              <i class="bi bi-gear me-2"></i>
              Constructor de Sitio
            </router-link>
          </li>
          <li class="nav-item">
            <router-link to="/settings" class="nav-link" active-class="active">
              <i class="bi bi-gear me-2"></i>
              Configuración
            </router-link>
          </li>
        </ul>
      </div>
    </nav>

    <!-- Main content -->
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 main-content">
      <!-- Top navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom mb-4">
        <div class="container-fluid">
          <button class="navbar-toggler d-md-none" type="button" @click="toggleSidebar">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="navbar-nav ms-auto">
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                <i class="bi bi-person-circle me-1"></i>
                {{ user?.name || 'Usuario' }}
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#" @click="logout">Cerrar Sesión</a></li>
              </ul>
            </div>
          </div>
        </div>
      </nav>

      <!-- Page content -->
      <router-view />
    </main>
  </div>
</template>

<script>
import { computed } from 'vue'
import { useAuthStore } from '../stores/auth.js'

export default {
  name: 'Layout',
  setup() {
    const authStore = useAuthStore()
    
    const user = computed(() => authStore.user.value)

    const logout = async () => {
      await authStore.logout()
      window.location.href = '/login'
    }

    const toggleSidebar = () => {
      // Implementar toggle para móviles si es necesario
      console.log('Toggle sidebar')
    }

    return {
      user,
      logout,
      toggleSidebar
    }
  }
}
</script>

// panel_admin/src/components/Layout.tsx
import { useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import { 
  LayoutDashboard, 
  FileText, 
  Database, 
  Eye, 
  Image, 
  Code, 
  Settings, 
  Menu, 
  X, 
  LogOut,
  User
} from 'lucide-react'

const navigation = [
  { name: 'Dashboard', href: '/dashboard', icon: LayoutDashboard },
  { name: 'Páginas', href: '/pages', icon: FileText },
  { name: 'Tipos de Contenido', href: '/content-types', icon: Database },
  { name: 'Vistas', href: '/views', icon: Eye },
  { name: 'Multimedia', href: '/media', icon: Image },
  { name: 'Formateadores', href: '/formatters', icon: Code },
  { name: 'Constructor de Sitio', href: '/site-builder', icon: Settings },
]

export default function Layout({ children }: { children: React.ReactNode }) {
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const location = useLocation()
  const { user, logout } = useAuth()

  const handleLogout = async () => {
    try {
      await logout()
    } catch (error) {
      console.error('Error during logout:', error)
    }
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Sidebar móvil */}
      <div className={`fixed inset-0 z-50 lg:hidden ${sidebarOpen ? 'block' : 'hidden'}`}>
        <div className="fixed inset-0 bg-gray-600 bg-opacity-75" onClick={() => setSidebarOpen(false)} />
        <div className="fixed inset-y-0 left-0 flex w-64 flex-col bg-white">
          <div className="flex h-16 items-center justify-between px-4">
            <h1 className="text-xl font-semibold text-gray-900">Static CMS</h1>
            <button
              onClick={() => setSidebarOpen(false)}
              className="text-gray-400 hover:text-gray-600"
            >
              <X className="h-6 w-6" />
            </button>
          </div>
          <nav className="flex-1 space-y-1 px-2 py-4">
            {navigation.map((item) => {
              const isActive = location.pathname === item.href
              return (
                <Link
                  key={item.name}
                  to={item.href}
                  className={`group flex items-center px-2 py-2 text-sm font-medium rounded-md ${
                    isActive
                      ? 'bg-primary-100 text-primary-900'
                      : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
                  }`}
                  onClick={() => setSidebarOpen(false)}
                >
                  <item.icon className="mr-3 h-5 w-5" />
                  {item.name}
                </Link>
              )
            })}
          </nav>
        </div>
      </div>

      {/* Sidebar desktop */}
      <div className="hidden lg:fixed lg:inset-y-0 lg:flex lg:w-64 lg:flex-col">
        <div className="flex flex-col flex-grow bg-white border-r border-gray-200">
          <div className="flex h-16 items-center px-4">
            <h1 className="text-xl font-semibold text-gray-900">Static CMS</h1>
          </div>
          <nav className="flex-1 space-y-1 px-2 py-4">
            {navigation.map((item) => {
              const isActive = location.pathname === item.href
              return (
                <Link
                  key={item.name}
                  to={item.href}
                  className={`group flex items-center px-2 py-2 text-sm font-medium rounded-md ${
                    isActive
                      ? 'bg-primary-100 text-primary-900'
                      : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
                  }`}
                >
                  <item.icon className="mr-3 h-5 w-5" />
                  {item.name}
                </Link>
              )
            })}
          </nav>
        </div>
      </div>

      {/* Contenido principal */}
      <div className="lg:pl-64">
        {/* Header */}
        <div className="sticky top-0 z-40 flex h-16 shrink-0 items-center gap-x-4 border-b border-gray-200 bg-white px-4 shadow-sm sm:gap-x-6 sm:px-6 lg:px-8">
          <button
            type="button"
            className="-m-2.5 p-2.5 text-gray-700 lg:hidden"
            onClick={() => setSidebarOpen(true)}
          >
            <Menu className="h-6 w-6" />
          </button>

          <div className="flex flex-1 gap-x-4 self-stretch lg:gap-x-6">
            <div className="flex flex-1" />
            <div className="flex items-center gap-x-4 lg:gap-x-6">
              {/* Perfil del usuario */}
              <div className="flex items-center gap-x-2">
                <User className="h-5 w-5 text-gray-400" />
                <span className="text-sm font-medium text-gray-900">
                  {user?.username}
                </span>
              </div>
              
              {/* Botón de logout */}
              <button
                onClick={handleLogout}
                className="flex items-center gap-x-2 text-sm font-medium text-gray-700 hover:text-gray-900"
              >
                <LogOut className="h-5 w-5" />
                Cerrar sesión
              </button>
            </div>
          </div>
        </div>

        {/* Contenido de la página */}
        <main className="py-6">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            {children}
          </div>
        </main>
      </div>
    </div>
  )
}
